name: "Changed files detection"
description: "Find the added and modified files due to a github event"
inputs:
  github-token:
    description: "Github access token."
    required: false
outputs:
  files:
    description: "Paths of all added or modified files"
    value: ${{ steps.changed-files.outputs.files }}
  files_including_removals:
    description: "Paths of all added, removed or modified files"
    value: ${{ steps.changed-files.outputs.files_including_removals }}
runs:
  using: "composite"
  steps:
    - name: "Get added and modified files"
      shell: bash
      id: changed-files
      run: |
        set -x
        ${{ github.action_path }}/find_changed_files.sh
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

