name: "AndroidX presubmit"
description: "Setup dev environment and runs the main AndroidX presubmit task, buildOnServer"
inputs:
  path:
    description: "Path of root project to build from"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Install Zulu JDK 11.0.9 (x64)"
      shell: bash
      run: |
        set -x

        if [ -d $HOME/jdk ]; then
          echo "JDK installation detected at $HOME/jdk"
          ls $HOME/jdk
          exit 0
        fi

        mkdir -p $HOME/jdk
        if [ "$RUNNER_OS" == "Linux" ]; then
          wget -q "https://cdn.azul.com/zulu/bin/zulu11.43.21-ca-jdk11.0.9-linux_x64.tar.gz" && \
          tar -C $HOME/jdk -xzf zulu11.43.21-ca-jdk11.0.9-linux_x64.tar.gz
          echo "JAVA_HOME=$HOME/jdk/zulu11.43.21-ca-jdk11.0.9-linux_x64" >> $GITHUB_ENV
        elif [ "$RUNNER_OS" == "macOS" ]; then
          wget -q "https://cdn.azul.com/zulu/bin/zulu11.43.21-ca-jdk11.0.9-macosx_x64.tar.gz" && \
          tar -C $HOME/jdk -xzf zulu11.43.21-ca-jdk11.0.9-macosx_x64.tar.gz
          echo "JAVA_HOME=$HOME/jdk/zulu11.43.21-ca-jdk11.0.9-macosx_x64" >> $GITHUB_ENV
        else
          echo "Unsupported OS: $RUNNER_OS"
          exit 1
        fi

    - name: "Set environment variables"
      shell: bash
      run: |
        echo "ANDROID_SDK_ROOT=$HOME/Library/Android/sdk" >> $GITHUB_ENV
        echo "DIST_DIR=$HOME/dist" >> $GITHUB_ENV

    - name: "Create output directory"
      shell: bash
      run: mkdir -p $DIST_DIR

    - name: "Run buildOnServer"
      shell: bash
      run: |
        set -x
        env
        cd ${{ inputs.path }} && ./gradlew :buildOnServer

